export { default as Tabs } from './Tabs.vue'
export { default as TabsList } from './TabsList.vue'
export { default as TabsTrigger } from './TabsTrigger.vue'
export { default as TabsContent } from './TabsContent.vue'
export { useTabsContext, type TabsContext } from './tabs.context'
export { tabsListVariants, type TabsVariant } from './tabs.variants'
